### PR TITLE
 Add package for scan, add refresh into context menu and fix one memory leak.

### PR DESCRIPTION
**Pull request by johny2000uwb**
Hi, 
First I would like to thank you for this plugin and offer you this pull request. I have made some our version of this plugin for our internal use. Now i have tried to use this actual version, but i have found some problems and hopefully fix it.
First of all, i have some really big cucumber Project, when i use this plugin, this plugin has been so slowly, that i cannot use it. Because it scan whole path. I have some Test project, so i do not have the feature in the same package as steps. So i have add in settings the possibility to define my own package for Steps scan. It rapidly improved the speed.
Second one, i have also problem with refactoring. I open the feature file, go to the steps and then i change the Expression, go back into feature file and i did not have any passibility to say, refresh steps now. I have add this functionality.
At third, when i work for a long time with this plugin, my eclipse has more then 2GB memory usage. I had used the memory analyser and i have found the memory leaks. I have fixed it. Hopefully. 

Thank again to whole team, who develop this plugin.

### CODE REVIEW

**Comment by mikejramsey56** [comment]
I am editing some large feature files mysel and the parsing is s-l-o-w; to the point of unusability. I had to uninstall this package and revert to natural. Are there any plans to merge this into a release?  The bulk of the feature file is example data so parsing that is just a waste of time.

**Comment by johny2000uwb** [comment]
I am waiting for any feedback. The scan of this files is really slow. This can help, i have added the possibility do define the path to scan. It helps rapidly. I cannot merge this pull request myself. And nobody react for two weeks.

**Comment by Jalaliel** [comment]
I think so yes. Do you need any help with that?

**Comment by aslakhellesoy** [comment]
Hi @johny2000uwb,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by ilanpillemer** [comment]
Thanks!

**Pull request merged**
