### PR TITLE
Issue 121

### PR DESCRIPTION
**Pull request by hdpe**
Fix for above issue. Includes integration of missing step marking into GherkinErrorMarker and refactoring for testability.

### CODE REVIEW

**Comment by ilanpillemer** [comment]
@hdpe Do we  still need to merge this in, based on your comments on #121

**Comment by hdpe** [comment]
@ilanpillemer this is a fix for #121 - there are no comments on #121 other than commit references for commits present in this PR - as far as I can see the need for the fix has not changed.

I just wanted to fix issues as I found them - if you could merge or provide feedback it would be much appreciated. I have a mountain of stuff ready to submit further PRs for in hdpe/cucumber-eclipse but don't want to swamp the mergers.

**Comment by ilanpillemer** [comment]
Much appreciated. Currently I am the only merger and I am very much in the
thick of a major global project with my paying my salary job. I took a
brief look and can't see any issues with your style.

I will have to trust you that it's all well tested and merge in then?

**Comment by hdpe** [comment]
Yup, I can confirm the tests pass and I've been using this fix in anger in my day job.

**Pull request merged**
