### PR TITLE
support built-in cucumber expressions

### PR DESCRIPTION
**Pull request by qvdk**
Add the support of built-in cucumber expressions.
screenshot from 2018-10-03 00-41-00

Previously, this type of expression crash the gherkin editor as described into #278 and #267 

Limitation: custom cucumber expressions are not detected.
screenshot from 2018-10-03 21-10-39

---

This path fixes also the issue #286.
When using a pattern like `@Given("^(?>region|regions) of type (.*) (?>are|is) covering all references$")`, the `StepMatcher` convert it as a malformed pattern `^(<p>|?>region|regions) of type (.*) (?>are|is) covering all references$`. 
More, it causes an exception with the side effect that the F3 key stop to work.

screenshot from 2018-10-04 00-16-26

### CODE REVIEW

**Comment by laeubi** [comment]
We have a similar problem, can this be merged or is there anything left?

**Comment by laeubi** [comment]
@johny2000uwb  Can this be merged or is there anything let to be done? I can verify that this fixes the issue at least for my test cases.
Since I'd like to improve the support for cucumber expressions it would be cool if we can have this merged first (+it would fix my issue with cucumber expressions failing at all atm)

**Comment by laeubi** [comment]
I can also verify that this fixes #286 (invalid regexp makes the parser crash)

**Comment by aslakhellesoy** [comment]
Hi @qvdk,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by qvdk** [comment]
Hi @aslakhellesoy Thanks for the invitation !

**Comment by danedb** [comment]
I really need this, is there a build available with this fix? Or when is next release scheduled?

**Pull request merged**
