### PR TITLE
Fix Issue 287 / 281

### LINKED ISSUE #281: Very slow opening feature file
It's taking 35s to open a 2k file with 1 feature having 2 scenario outlines.

Using Eclipse Photon 4.8 20180619-1200 and Cucumber Eclipse Feature 0.0.22.201806032001

### PR DESCRIPTION
**Pull request by laeubi**
- fixes Issue #287 
- fixes #281 since it schedules the loading of step defs in the background, the steps are highlighted as soon as the loading process is done but the editor opens instantly

### CODE REVIEW

**Comment by johny2000uwb** [comment]
Cool !

**Comment by girijant** [comment]
@laeubi,
Your pull request will be only merged in 'master' branch. But I am expecting same updates in 'gh-pages' branch also. As I've recently merged 2 pull requests, so please download latest code from 'master' branch, update master with your fixes and fire a build from the master and update 'gh-pages' branch accordingly after building master. By updating both master and gh-pages branches with your latest fix, send new pull requests for both master and gh-pages branches. Then I can merge both requests. Else your fixes will not be reflected in eclipse-update sites.

Thaks,
-Girija

**Comment by laeubi** [comment]
@girijant I'll try that, just wondering, github says there is no conflict with the master branch.
Comparing the gh-branch githib says:

There isn’t anything to compare. cucumber:gh-pages is up to date with all commits from laeubi:gh-pages. Try switching the base for your comparison.

So is there really anything to do?

**Comment by qvdk** [comment]
Hi @laeubi 
Your branch issue-287 is behind 7 commits from cucumber:master.
```
# add an upstream with official repository
git remote add upstream https://github.com/cucumber/cucumber-eclipse.git
# go to master
git checkout master
# pull with upstream:master
git pull upstream master
# sync your PR 
git checkout issue-287
git rebase master
git push
```

**Comment by qvdk** [comment]
I think you will fix also the #273 :+1:

**Comment by laeubi** [comment]
@qvdk I merged the master branch into my branch and pushed it, hope this helps

**Comment by laeubi** [comment]
@girijant can you please check if now everything is fine? Since github says the PR can be merged I don'T understand the issue, sorry :-(

**Comment by qvdk** [comment]
@laeubi He asked to rebase your branch with the latest `cucumber:master` (there are 7 commits behind). I described how to do it in my previous comment if needed.

screenshot from 2018-11-20 22-13-26

More, he asked to update the `gh-pages` branch to introduce yours improvements :)
This branch is used to update the official website of the plugin : https://cucumber.io/cucumber-eclipse/

**Comment by qvdk** [comment]
@laeubi I rebase your branch. Your patch is now ahead of the latest version of `cucumber:master`

screenshot from 2018-11-20 23-30-46

**Comment by qvdk** [comment]
This patch works great. I just tried it with the sample of the issue #287 

Before / After
screenshot from 2018-11-20 23-38-27

No more warning for non matching glue code, and press <kbd>F3</kbd> jump to the related one.

**Comment by qvdk** [comment]
@girijant I just take a look on how works gh-pages for this project. 

So, I suggest to merge this pull request. 
Then, I will update my pull request #290 with this previous merge.
Then, I will make a new pull request for gh-pages with a new post and new archives.

**Comment by aslakhellesoy** [comment]
Hi @laeubi,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
