### PR TITLE
Issue #291 Create JavaBackend to support custom Factories

### PR DESCRIPTION
**Pull request by laeubi**
This adds a new configuration option to the project so you can activate the JavaBackend, this feature is a little bit experimental and we would need to check how it behaves in the wild so it is diabled by default.

With this backend activated, the classpath is scanned for TypeRegsitryConfigurers like done with Cucumber, the configurer is the used to create an ExpressionFactory.

If this works well, we can enhance this to let the Backend do all the hard stuff (finding glue codes, generate snippets and so on), and then it would also be possible to support additional languages (JS, Ruby, ...) with different Backends for the Eclipse plugin.

### CODE REVIEW

**Comment by qvdk** [comment]
I don't understand why, but the `StepDefinitionsRepositoryTest` success with `mvn clean test` but not with `mvn clean install`.
Could you take a look please ?
I will change the .travis.yml to replace the mvn verify.

**Comment by laeubi** [comment]
It seems tycho requires the "integration-test" phase, will fix that...

**Comment by laeubi** [comment]
The tests are running now, but it seem that travis does not over an UI (and at least in my local machine the tests open a window for a short time)

**Comment by laeubi** [comment]
I have enabled xvfb but it still complains:
** (java:4855): WARNING **: Could not open X display

**Pull request merged**
